// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOPlIEvTjAnEwj4v01kC2GZNNjyZ93QI',
    appId: '1:269846928993:web:7456367040b6376d959420',
    messagingSenderId: '269846928993',
    projectId: 'whatsapp-clone-d4e5c',
    authDomain: 'whatsapp-clone-d4e5c.firebaseapp.com',
    storageBucket: 'whatsapp-clone-d4e5c.appspot.com',
    measurementId: 'G-ERT12BXVCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5b8Hs-5p9DSG-rCMpXvSAJNIf-gATM08',
    appId: '1:269846928993:android:ce5481edc40961de959420',
    messagingSenderId: '269846928993',
    projectId: 'whatsapp-clone-d4e5c',
    storageBucket: 'whatsapp-clone-d4e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA49X5faSaqeC2diy-bymR-3-aF4F-LaiE',
    appId: '1:269846928993:ios:d429ec684a7cc9b2959420',
    messagingSenderId: '269846928993',
    projectId: 'whatsapp-clone-d4e5c',
    storageBucket: 'whatsapp-clone-d4e5c.appspot.com',
    iosClientId: '269846928993-vqc3k0352fiu5b3f4a08hu9025n34rod.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA49X5faSaqeC2diy-bymR-3-aF4F-LaiE',
    appId: '1:269846928993:ios:d429ec684a7cc9b2959420',
    messagingSenderId: '269846928993',
    projectId: 'whatsapp-clone-d4e5c',
    storageBucket: 'whatsapp-clone-d4e5c.appspot.com',
    iosClientId: '269846928993-vqc3k0352fiu5b3f4a08hu9025n34rod.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
